spring:
  application:
    name: meditlink-commerce-core-service

  # core-service 전용 DB
  datasource:
    url: jdbc:postgresql://localhost:5432/meditlink_commerce
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  # Liquibase로 DDL 이력 관리
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081

# integration-layer가 호출할 gRPC 서버 포트
grpc:
  server:
    port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,info
