syntax = "proto3";

package commerce.v1;

option java_package = "com.meditlink.poc.commerce.common.proto.v1";
option java_multiple_files = true;

service ProductService {
  rpc CreateProduct(CreateProductRequest) returns (CreateProductResponse);
  rpc GetProduct(GetProductRequest) returns (GetProductResponse);
}

message CreateProductRequest {
  string sku = 1;
  string name = 2;
  int64 base_price = 3;
  string currency = 4;
}

message CreateProductResponse {
  string product_id = 1;
}

message GetProductRequest {
  string product_id = 1;
}

message GetProductResponse {
  string product_id = 1;
  string sku = 2;
  string name = 3;
  int64 base_price = 4;
  string currency = 5;
  bool found = 6;
}
